---
abstract: 'Facilitates the creation and modification of PDF files'
author:
  - 'Steve Simms <steve@deefs.net>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
generated_by: 'Module::Build version 0.3603'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PDF-API2
provides:
  PDF::API2:
    file: lib/PDF/API2.pm
  PDF::API2::Annotation:
    file: lib/PDF/API2/Annotation.pm
  PDF::API2::Basic::PDF::Array:
    file: lib/PDF/API2/Basic/PDF/Array.pm
  PDF::API2::Basic::PDF::Bool:
    file: lib/PDF/API2/Basic/PDF/Bool.pm
  PDF::API2::Basic::PDF::Dict:
    file: lib/PDF/API2/Basic/PDF/Dict.pm
  PDF::API2::Basic::PDF::File:
    file: lib/PDF/API2/Basic/PDF/File.pm
  PDF::API2::Basic::PDF::Filter:
    file: lib/PDF/API2/Basic/PDF/Filter.pm
  PDF::API2::Basic::PDF::Filter::ASCII85Decode:
    file: lib/PDF/API2/Basic/PDF/Filter/ASCII85Decode.pm
  PDF::API2::Basic::PDF::Filter::ASCIIHexDecode:
    file: lib/PDF/API2/Basic/PDF/Filter/ASCIIHexDecode.pm
  PDF::API2::Basic::PDF::Filter::FlateDecode:
    file: lib/PDF/API2/Basic/PDF/Filter/FlateDecode.pm
  PDF::API2::Basic::PDF::Filter::LZWDecode:
    file: lib/PDF/API2/Basic/PDF/Filter/LZWDecode.pm
  PDF::API2::Basic::PDF::Filter::RunLengthDecode:
    file: lib/PDF/API2/Basic/PDF/Filter/RunLengthDecode.pm
  PDF::API2::Basic::PDF::Literal:
    file: lib/PDF/API2/Basic/PDF/Literal.pm
  PDF::API2::Basic::PDF::Name:
    file: lib/PDF/API2/Basic/PDF/Name.pm
  PDF::API2::Basic::PDF::Null:
    file: lib/PDF/API2/Basic/PDF/Null.pm
  PDF::API2::Basic::PDF::Number:
    file: lib/PDF/API2/Basic/PDF/Number.pm
  PDF::API2::Basic::PDF::Objind:
    file: lib/PDF/API2/Basic/PDF/Objind.pm
  PDF::API2::Basic::PDF::Page:
    file: lib/PDF/API2/Basic/PDF/Page.pm
  PDF::API2::Basic::PDF::Pages:
    file: lib/PDF/API2/Basic/PDF/Pages.pm
  PDF::API2::Basic::PDF::String:
    file: lib/PDF/API2/Basic/PDF/String.pm
  PDF::API2::Basic::PDF::Utils:
    file: lib/PDF/API2/Basic/PDF/Utils.pm
  PDF::API2::Build::Version:
    file: lib/PDF/API2/Build/Version.pm
    version: 0
  PDF::API2::Content:
    file: lib/PDF/API2/Content.pm
  PDF::API2::Content::Text:
    file: lib/PDF/API2/Content/Text.pm
  PDF::API2::Lite:
    file: lib/PDF/API2/Lite.pm
  PDF::API2::Matrix:
    file: lib/PDF/API2/Matrix.pm
  PDF::API2::NamedDestination:
    file: lib/PDF/API2/NamedDestination.pm
  PDF::API2::Outline:
    file: lib/PDF/API2/Outline.pm
  PDF::API2::Outlines:
    file: lib/PDF/API2/Outlines.pm
  PDF::API2::Page:
    file: lib/PDF/API2/Page.pm
  PDF::API2::Resource:
    file: lib/PDF/API2/Resource.pm
  PDF::API2::Resource::BaseFont:
    file: lib/PDF/API2/Resource/BaseFont.pm
  PDF::API2::Resource::CIDFont:
    file: lib/PDF/API2/Resource/CIDFont.pm
  PDF::API2::Resource::CIDFont::CJKFont:
    file: lib/PDF/API2/Resource/CIDFont/CJKFont.pm
  PDF::API2::Resource::CIDFont::TrueType:
    file: lib/PDF/API2/Resource/CIDFont/TrueType.pm
  PDF::API2::Resource::CIDFont::TrueType::FontFile:
    file: lib/PDF/API2/Resource/CIDFont/TrueType/FontFile.pm
  PDF::API2::Resource::ColorSpace:
    file: lib/PDF/API2/Resource/ColorSpace.pm
  PDF::API2::Resource::ColorSpace::DeviceN:
    file: lib/PDF/API2/Resource/ColorSpace/DeviceN.pm
  PDF::API2::Resource::ColorSpace::Indexed:
    file: lib/PDF/API2/Resource/ColorSpace/Indexed.pm
  PDF::API2::Resource::ColorSpace::Indexed::ACTFile:
    file: lib/PDF/API2/Resource/ColorSpace/Indexed/ACTFile.pm
  PDF::API2::Resource::ColorSpace::Indexed::Hue:
    file: lib/PDF/API2/Resource/ColorSpace/Indexed/Hue.pm
  PDF::API2::Resource::ColorSpace::Indexed::WebColor:
    file: lib/PDF/API2/Resource/ColorSpace/Indexed/WebColor.pm
  PDF::API2::Resource::ColorSpace::Separation:
    file: lib/PDF/API2/Resource/ColorSpace/Separation.pm
  PDF::API2::Resource::Colors:
    file: lib/PDF/API2/Resource/Colors.pm
  PDF::API2::Resource::ExtGState:
    file: lib/PDF/API2/Resource/ExtGState.pm
  PDF::API2::Resource::Font:
    file: lib/PDF/API2/Resource/Font.pm
  PDF::API2::Resource::Font::BdFont:
    file: lib/PDF/API2/Resource/Font/BdFont.pm
  PDF::API2::Resource::Font::CoreFont:
    file: lib/PDF/API2/Resource/Font/CoreFont.pm
  PDF::API2::Resource::Font::CoreFont::bankgothic:
    file: lib/PDF/API2/Resource/Font/CoreFont/bankgothic.pm
  PDF::API2::Resource::Font::CoreFont::courier:
    file: lib/PDF/API2/Resource/Font/CoreFont/courier.pm
  PDF::API2::Resource::Font::CoreFont::courierbold:
    file: lib/PDF/API2/Resource/Font/CoreFont/courierbold.pm
  PDF::API2::Resource::Font::CoreFont::courierboldoblique:
    file: lib/PDF/API2/Resource/Font/CoreFont/courierboldoblique.pm
  PDF::API2::Resource::Font::CoreFont::courieroblique:
    file: lib/PDF/API2/Resource/Font/CoreFont/courieroblique.pm
  PDF::API2::Resource::Font::CoreFont::georgia:
    file: lib/PDF/API2/Resource/Font/CoreFont/georgia.pm
  PDF::API2::Resource::Font::CoreFont::georgiabold:
    file: lib/PDF/API2/Resource/Font/CoreFont/georgiabold.pm
  PDF::API2::Resource::Font::CoreFont::georgiabolditalic:
    file: lib/PDF/API2/Resource/Font/CoreFont/georgiabolditalic.pm
  PDF::API2::Resource::Font::CoreFont::georgiaitalic:
    file: lib/PDF/API2/Resource/Font/CoreFont/georgiaitalic.pm
  PDF::API2::Resource::Font::CoreFont::helvetica:
    file: lib/PDF/API2/Resource/Font/CoreFont/helvetica.pm
  PDF::API2::Resource::Font::CoreFont::helveticabold:
    file: lib/PDF/API2/Resource/Font/CoreFont/helveticabold.pm
  PDF::API2::Resource::Font::CoreFont::helveticaboldoblique:
    file: lib/PDF/API2/Resource/Font/CoreFont/helveticaboldoblique.pm
  PDF::API2::Resource::Font::CoreFont::helveticaoblique:
    file: lib/PDF/API2/Resource/Font/CoreFont/helveticaoblique.pm
  PDF::API2::Resource::Font::CoreFont::symbol:
    file: lib/PDF/API2/Resource/Font/CoreFont/symbol.pm
  PDF::API2::Resource::Font::CoreFont::timesbold:
    file: lib/PDF/API2/Resource/Font/CoreFont/timesbold.pm
  PDF::API2::Resource::Font::CoreFont::timesbolditalic:
    file: lib/PDF/API2/Resource/Font/CoreFont/timesbolditalic.pm
  PDF::API2::Resource::Font::CoreFont::timesitalic:
    file: lib/PDF/API2/Resource/Font/CoreFont/timesitalic.pm
  PDF::API2::Resource::Font::CoreFont::timesroman:
    file: lib/PDF/API2/Resource/Font/CoreFont/timesroman.pm
  PDF::API2::Resource::Font::CoreFont::trebuchet:
    file: lib/PDF/API2/Resource/Font/CoreFont/trebuchet.pm
  PDF::API2::Resource::Font::CoreFont::trebuchetbold:
    file: lib/PDF/API2/Resource/Font/CoreFont/trebuchetbold.pm
  PDF::API2::Resource::Font::CoreFont::trebuchetbolditalic:
    file: lib/PDF/API2/Resource/Font/CoreFont/trebuchetbolditalic.pm
  PDF::API2::Resource::Font::CoreFont::trebuchetitalic:
    file: lib/PDF/API2/Resource/Font/CoreFont/trebuchetitalic.pm
  PDF::API2::Resource::Font::CoreFont::verdana:
    file: lib/PDF/API2/Resource/Font/CoreFont/verdana.pm
  PDF::API2::Resource::Font::CoreFont::verdanabold:
    file: lib/PDF/API2/Resource/Font/CoreFont/verdanabold.pm
  PDF::API2::Resource::Font::CoreFont::verdanabolditalic:
    file: lib/PDF/API2/Resource/Font/CoreFont/verdanabolditalic.pm
  PDF::API2::Resource::Font::CoreFont::verdanaitalic:
    file: lib/PDF/API2/Resource/Font/CoreFont/verdanaitalic.pm
  PDF::API2::Resource::Font::CoreFont::webdings:
    file: lib/PDF/API2/Resource/Font/CoreFont/webdings.pm
  PDF::API2::Resource::Font::CoreFont::wingdings:
    file: lib/PDF/API2/Resource/Font/CoreFont/wingdings.pm
  PDF::API2::Resource::Font::CoreFont::zapfdingbats:
    file: lib/PDF/API2/Resource/Font/CoreFont/zapfdingbats.pm
  PDF::API2::Resource::Font::Postscript:
    file: lib/PDF/API2/Resource/Font/Postscript.pm
  PDF::API2::Resource::Font::SynFont:
    file: lib/PDF/API2/Resource/Font/SynFont.pm
  PDF::API2::Resource::Glyphs:
    file: lib/PDF/API2/Resource/Glyphs.pm
  PDF::API2::Resource::PaperSizes:
    file: lib/PDF/API2/Resource/PaperSizes.pm
  PDF::API2::Resource::Pattern:
    file: lib/PDF/API2/Resource/Pattern.pm
  PDF::API2::Resource::Shading:
    file: lib/PDF/API2/Resource/Shading.pm
  PDF::API2::Resource::UniFont:
    file: lib/PDF/API2/Resource/UniFont.pm
  PDF::API2::Resource::XObject:
    file: lib/PDF/API2/Resource/XObject.pm
  PDF::API2::Resource::XObject::Form:
    file: lib/PDF/API2/Resource/XObject/Form.pm
  PDF::API2::Resource::XObject::Form::BarCode:
    file: lib/PDF/API2/Resource/XObject/Form/BarCode.pm
  PDF::API2::Resource::XObject::Form::BarCode::codabar:
    file: lib/PDF/API2/Resource/XObject/Form/BarCode/codabar.pm
  PDF::API2::Resource::XObject::Form::BarCode::code128:
    file: lib/PDF/API2/Resource/XObject/Form/BarCode/code128.pm
  PDF::API2::Resource::XObject::Form::BarCode::code3of9:
    file: lib/PDF/API2/Resource/XObject/Form/BarCode/code3of9.pm
  PDF::API2::Resource::XObject::Form::BarCode::ean13:
    file: lib/PDF/API2/Resource/XObject/Form/BarCode/ean13.pm
  PDF::API2::Resource::XObject::Form::BarCode::int2of5:
    file: lib/PDF/API2/Resource/XObject/Form/BarCode/int2of5.pm
  PDF::API2::Resource::XObject::Form::Hybrid:
    file: lib/PDF/API2/Resource/XObject/Form/Hybrid.pm
  PDF::API2::Resource::XObject::Image:
    file: lib/PDF/API2/Resource/XObject/Image.pm
  PDF::API2::Resource::XObject::Image::GD:
    file: lib/PDF/API2/Resource/XObject/Image/GD.pm
  PDF::API2::Resource::XObject::Image::GIF:
    file: lib/PDF/API2/Resource/XObject/Image/GIF.pm
  PDF::API2::Resource::XObject::Image::JPEG:
    file: lib/PDF/API2/Resource/XObject/Image/JPEG.pm
  PDF::API2::Resource::XObject::Image::PNG:
    file: lib/PDF/API2/Resource/XObject/Image/PNG.pm
  PDF::API2::Resource::XObject::Image::PNM:
    file: lib/PDF/API2/Resource/XObject/Image/PNM.pm
  PDF::API2::Resource::XObject::Image::TIFF:
    file: lib/PDF/API2/Resource/XObject/Image/TIFF.pm
  PDF::API2::Resource::XObject::Image::Tiff::File:
    file: lib/PDF/API2/Resource/XObject/Image/TIFF.pm
  PDF::API2::UniWrap:
    file: lib/PDF/API2/UniWrap.pm
  PDF::API2::Util:
    file: lib/PDF/API2/Util.pm
  PDF::API2::Win32:
    file: lib/PDF/API2/Win32.pm
requires:
  Compress::Zlib: 1.0
  Font::TTF: 0
  perl: v5.8.1
resources:
  license: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
version: 2.019
